### ISSUE TITLE
ModelTrackerMiddleware and Migrations

### ISSUE THREAD

**Issue by Bchass** [mkalioby/ModelTracker#1]
I recently came across this package and provides the solution I've been looking for. I'm having a couple of issues that don't completely make sense on what is going wrong.

### 1. Middleware

I added `ModelTracker.middleware.ModelTrackerMiddleware` to my middleware section and I get the following error: `TypeError: ModelTrackerMiddleware() takes no arguments`. I believe this may have to do with the migration issues I'm facing with this pacakge. See below.

### 2. Migrations

When starting my application I can see there are changes that haven't been applied to the ModelTracker app: `Your models in app(s): 'ModelTracker' have changes that are not yet reflected in a migration, and so won't be applied.
test_django |   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.`

I followed the directions on the Installation step that calls for `python manage.py migrate ModelTracker`. When I apply the migrations: 
`Operations to perform:
       Apply all migrations: ModelTracker
Running migrations:
       No migrations to apply.`

The only thing that is working at the moment is the tracking page. I've registered a model to inherit `Tracker.ModelTracker` but it does not show in the dropdown for Models. I think this is all tied back to the migrations. 

Django: `3.2`
Python: `3.9`
django-model-tracker: `2.0.3`
jsonfield: `3.1.0`

**Comment by mkalioby** [comment]
Hello, 

Sorry to hear that.

Your issue is mainly the middleware. Please upgrade to [v2.1.0b1](https://pypi.org/project/django-model-tracker/2.1.0b1/) and it shall work.

**Comment by Bchass** [comment]
Thanks! Your recent changes have fixed the issue.
