### ISSUE TITLE
Track changes by username or user_id?

### ISSUE THREAD

**Issue by Bchass** [mkalioby/ModelTracker#3]
Upon exploring the tracking page I noticed you need to know the object ID to see the recent changes. This isn't intuitive as a user doesn't know what that ID would be unless they have access to the dbase.

How about the tracking page pulls all usernames or user_id's and be able to select one and have all the changes displayed on the screen at once?

This would be another dropdown menu that lists all active users.

**Comment by Bchass** [comment]
Or the ability to type in a username and see all the changes that user has made.

**Comment by mkalioby** [comment]
This tracking page is designed for system admins.
The id is the object id not the users. The idea of app is object tracking and not user tracking.

You can choose between point 2 and 3 in View Record History section to be user friendly. For example  in object page, have a button called 'history' which will call the endpoint in point 2 and show response in a modal.

**Comment by Bchass** [comment]
I understand now. Do you have an example of a local app using point 2? I'd like to play around with it and make my own changes locally first. I think an example would also be helpful for the readme.

Thanks!

**Comment by mkalioby** [comment]
This needs a full app with add, edit and view features, and currently i dont have time for that, if you create the app, I can show you how to use option 2.

**Comment by Bchass** [comment]
I do have an app in a test env that is hooked into a test dbase that can add, edit and view.

**Comment by mkalioby** [comment]
here is the js code to put in the template using bootstrap 3/4 modal.

```javascript
   function gotoModalTracker() {
           $("#modal-title").html("Data Tracker")
           $("#modal-body").html("Loading Data....")
            $("#popUpModal").modal()
              $.ajax({
                url:"{% url 'showModelChanges' %}",data:{"table":"SQL_TABLE_NAME","csrfmiddlewaretoken":'{{ csrf_token }}',"id":{{ obj.id }}},method:"POST",
                success:function(data) {
                    $("#modal-body").css({"overflow-y":"scroll","height":"70vh"})
                    $("#modal-body").html(data)
            }
            })
    }
```
If you need help, please share your code

**Comment by mkalioby** [comment]
Closed for inactivity
